image: node:10.19
cache:
  paths:
    - .cache/
    - public/
    - node_modules/

pages:
  script:
    - npm install
    - ./node_modules/.bin/gatsby build --prefix-paths
  artifacts:
    paths:
      - public
  only:
    - master

preview:
  script:
    - npm install
    - ./node_modules/.bin/gatsby build --prefix-paths
  environment:
    name: preview
    url: https://gitlab.com/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/-/jobs/${CI_JOB_ID}/artifacts/browse/public/index.html
  artifacts:
    paths:
      - public
  except:
    - master
