image: node:10.19
cache:
  paths:
    - .cache/
    - public/
    - node_modules/
variables:
  PREVIEW_LINK: https://gitlab.com/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/-/jobs/${CI_JOB_ID}/artifacts/file/public/index.html
stages:
  - announce_preview_start
  - build
  - announce_preview_end

pages:
  stage: build
  script:
    - npm install
    - ./node_modules/.bin/gatsby build --prefix-paths
  artifacts:
    paths:
      - public
  only:
    - master

announce_preview_start:
  stage: announce_preview_start
  script: >
    curl
    --request POST
    --header "PRIVATE-TOKEN: ${CI_JOB_TOKEN}"
    --data-urlencode "state=running"
    --data-urlencode "name=preview_status"
    "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/statuses/${CI_COMMIT_SHA}"
  except:
    - master

preview:
  stage: build
  script:
    - npm install
    - ./node_modules/.bin/gatsby build --prefix-paths
  environment:
    name: preview
    url: ${PREVIEW_LINK}
  artifacts:
    paths:
      - public
  except:
    - master

announce_preview_end_success:
  stage: announce_preview_end
  script: >
    curl
    --request POST
    --header "PRIVATE-TOKEN: ${CI_JOB_TOKEN}"
    --data-urlencode "target_url=${PREVIEW_LINK}"
    --data-urlencode "state=success"
    --data-urlencode "name=preview_status"
    "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/statuses/${CI_COMMIT_SHA}"
  when: on_success
  except:
    - master

announce_preview_end_failure:
  stage: announce_preview_end
  script: >
    curl
    --request POST
    --header "PRIVATE-TOKEN: ${CI_JOB_TOKEN}"
    --data-urlencode "state=failed"
    --data-urlencode "name=preview_status"
    "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/statuses/${CI_COMMIT_SHA}"
  when: on_failure
  except:
    - master
