image: node:10.19
cache:
  paths:
    - .cache/
    - public/
    - node_modules/
variables:
  PREVIEW_PATH: preview/${CI_JOB_ID}/
stages:
  - build
  - announce_preview_end

pages:
  stage: build
  script:
    - >
      curl
      --request POST
      --header "PRIVATE-TOKEN: ${API_TOKEN}"
      --data-urlencode "state=running"
      --data-urlencode "name=preview_status"
      "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/statuses/${CI_COMMIT_SHA}"
    - npm install
    - >
      if ["$CI_COMMIT_REF_NAME" != "master"]; then
        sed -i -e "s#pathPrefix: \"/\"#pathPrefix: \"/${PREVIEW_PATH}\"#g" gatsby-config.js
      fi
    - mkdir -p public/preview/
    - mv public old_public
    - ./node_modules/.bin/gatsby build --prefix-paths
    - mv public/* old_public/preview/${CI_JOB_ID}/
    - >
      if ["$CI_COMMIT_REF_NAME" == "master"]; then
        mv old_public/preview/${CI_JOB_ID}/* public/
        mv old_public/preview/* public/preview/
      else;
        mv old_public/* public/
      fi
    - >
      curl
      --request POST
      --header "PRIVATE-TOKEN: ${API_TOKEN}"
      --data-urlencode "target_url=${CI_PAGES_URL}/${PREVIEW_PATH}"
      --data-urlencode "state=success"
      --data-urlencode "name=preview_status"
      "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/statuses/${CI_COMMIT_SHA}"
  environment:
    name: preview
    url: ${CI_PAGES_URL}/${PREVIEW_PATH}
  artifacts:
    paths:
      - public

announce_preview_end_failure:
  stage: announce_preview_end
  script: >
    curl
    --request POST
    --header "PRIVATE-TOKEN: ${CI_JOB_TOKEN}"
    --data-urlencode "state=failed"
    --data-urlencode "name=preview_status"
    "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/statuses/${CI_COMMIT_SHA}"
  when: on_failure
