backend:
  name: gitlab
  preview_context: preview_status
  repo: tedxwarsaw/tedxwarsaw.gitlab.io
publish_mode: editorial_workflow
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home" # Used in the UI
        name: "home"
        file: "src/pages/content/pages/index.yaml"
        slug: "index.md" # Filename template, e.g., YYYY-MM-DD-title.md
        fields: # The fields for each document, usually in front matter
          - label: "Hero title"
            name: "heroTitle"
            widget: "string"
          - label: "Hero subtitle"
            name: "heroSubtitle"
            widget: "string"
          - label: "Hero button text"
            name: "heroButtonText"
            widget: "string"
          - label: "Hero button link"
            name: "heroButtonLink"
            widget: "string"
          - label: "Hero links"
            name: "heroLinks"
            widget: "list"
            fields:
              - { label: "Display name", name: "displayName", widget: "string" }
              - { label: "Path", name: "path", widget: "string" }
          - label: "Hero background mobile image"
            name: "heroBackgroundImageUrl"
            widget: image
            allow_multiple: false
            media_folder: "photos"
          - label: "Hero background desktop image"
            name: "heroBackgroundImageUrlDesktop"
            widget: image
            allow_multiple: false
            media_folder: "photos"
          - label: "Hero background image alt"
            name: "heroBackgroundImageAlt"
            widget: string
          - label: "Our story section title"
            name: "ourStoryTitle"
            widget: string
          - label: "Our story section items"
            name: "ourStoryItems"
            widget: "list"
            fields:
              - { label: "Bold text", name: "boldText", widget: "string" }
              - { label: "Text", name: "text", widget: "string" }
          - name: recommendations
            label: "Recommendations"
            widget: object
            hint: "Events and talks that will be shown in the recommendations slider"
            fields:
              - name: "events"
                label: "Events"
                widget: list
                fields:
                  - {
                      label: "Event",
                      name: "eventSlug",
                      widget: "relation",
                      collection: events,
                      value_field: "slug",
                      display_fields: ["displayName"],
                      search_fields: ["displayName", "slug"],
                    }
                  - {
                      label: "Order",
                      name: "order",
                      widget: number,
                      hint: "Order number in which this item will be displayed on the slider",
                    }
              - name: "talks"
                label: "Talks"
                widget: list
                fields:
                  - {
                      label: "Talk",
                      name: "talkSlug",
                      widget: "relation",
                      collection: talks,
                      value_field: "slug",
                      display_fields: ["displayName"],
                      search_fields: ["displayName", "slug"],
                    }
                  - {
                      label: "Order",
                      name: "order",
                      widget: number,
                      hint: "Order number in which this item will be displayed on the slider",
                    }
          - name: eventSlug
            label: Event
            widget: relation
            collection: events
            value_field: slug
            display_fields: ["displayName"]
            search_fields: ["displayName", "slug"]
          - label: Youtube banner heading
            name: youtubeBannerHeading
            hint: "This field supports HTML syntax"
            widget: string
          - label: Youtube banner button text
            name: youtubeBannerLinkText
            widget: string
          - label: Youtube banner button link
            name: youtubeBannerLinkUrl
            widget: string
          - label: Join us section title
            name: joinUsTitle
            widget: string
          - label: Join us section subtitle
            name: joinUsSubtitle
            widget: string
          - label: "Join us section image"
            name: "joinUsImagePath"
            widget: image
            allow_multiple: false
            media_folder: "photos"
          - label: "Join us section image desktop"
            name: "joinUsImageDesktopPath"
            widget: image
            allow_multiple: false
            media_folder: "photos"
          - label: Join us volunteer link text
            name: joinUsVolunteerText
            widget: string
          - label: Join us volunteer link
            name: joinUsVolunteerLink
            widget: string
          - label: Get to know our team link text
            name: joinUsGetToKnowOurTeamText
            widget: string
          - label: Get to know our team link
            name: joinUsGetToKnowOurTeamLink
            widget: string
          - label: Become speaker link text
            name: joinUsBecomeSpeakerText
            widget: string
          - label: Become speaker link
            name: joinUsBecomeSpeakerLink
            widget: string
          - label: Partner section title
            name: partnerSectionTitle
            widget: string
          - label: Get to know our partners link text
            name: getToKnowOurPartnersText
            widget: string
          - label: Get to know our partners link
            name: getToKnowOurPartnersLink
            widget: string
          - label: Join our partners link text
            name: joinOurPartnersText
            widget: string
          - label: Join our partners link
            name: joinOurPartnersLink
            widget: string
          - name: partnerLogoPaths
            label: Partner Logos
            widget: image
            allow_multiple: true
            media_folder: "photos/partnerLogos"
            media_library:
              config:
                multiple: true
  - label: "Global"
    name: "global"
    files:
      - label: "Navbar"
        name: "navbar"
        file: "src/pages/content/global/navbar.yaml"
        fields:
          - name: collectionId
            widget: hidden
            default: navbar
          - label: Navbar Links
            name: navbarLinks
            widget: list
            fields:
              - { label: "Display Name", name: "displayName", widget: "string" }
              - { label: "Path", name: "path", widget: "string" }
              - label: "Variant"
                name: "variant"
                widget: "select"
                options: ["red", "black"]
          - label: Navbar Buttons
            name: navbarButtons
            widget: list
            fields:
              - { label: "Display Name", name: "displayName", widget: "string" }
              - { label: "Path", name: "path", widget: "string" }
              - { label: "Is Tooltip", name: "isTooltip", widget: "boolean" }
              - label: "Variant"
                name: "variant"
                widget: "select"
                options: ["red", "black"]
              - label: "Tooltip Contents"
                name: tooltipContents
                widget: list
                fields:
                  - { label: Title, name: title, widget: string }
                  - { label: Description, name: description, widget: string }
                  - { label: Path, name: path, widget: string }
      - label: "Footer"
        name: "footer"
        file: "src/pages/content/global/footer.yaml"
        fields:
          - name: collectionId
            widget: hidden
            default: footer
          - label: Second Column
            name: footerSecondColumn
            widget: object
            fields:
              - {
                  label: "Column Header",
                  name: "displayName",
                  widget: "string",
                }
              - name: links
                label: Links
                widget: list
                fields:
                  - name: displayName
                    label: Display Name
                    widget: string
                  - name: path
                    label: Path
                    widget: string
                    pattern: ["^/.+$", "it must start with '/'"]
          - label: Third Column
            name: footerThirdColumn
            widget: object
            fields:
              - {
                  label: "Column Header",
                  name: "displayName",
                  widget: "string",
                }
              - name: links
                label: Links
                widget: list
                fields:
                  - name: displayName
                    label: Display Name
                    widget: string
                  - name: path
                    label: Path
                    widget: string
                    pattern: ["^/.+$", "it must start with '/'"]
      - label: "Partnership Team (shown on all event pages)"
        name: "partnershipTeam"
        file: "src/pages/content/global/events/partnershipTeam/partnershipTeam.yaml"
        fields:
          - name: collectionId
            widget: hidden
            default: eventPartnershipTeam
          - name: members
            label: Team Members
            hint: "Partnership team members are shown on every event page."
            widget: list
            fields:
              - name: name
                label: Name
                widget: string
              - name: areaOfResponsibility
                label: Area of Responsibility
                widget: string
              - name: phoneNumber
                label: Phone Number
                widget: string
              - name: email
                label: Email
                widget: string
              - name: photo
                label: Photo
                widget: image
                allow_multiple: false
                media_folder: "photos"
      - label: "Suggested Event (shown on all event pages)"
        name: "suggestedEvent"
        file: "src/pages/content/global/events/suggestedEvent/suggestedEvent.yaml"
        fields:
          - name: collectionId
            widget: hidden
            default: suggestedEvent
          - name: slug
            label: Event
            widget: relation
            collection: events
            value_field: slug
            display_fields: ["displayName"]
            search_fields: ["displayName", "slug"]
          - name: photos
            label: Featured Photos
            widget: image
            allow_multiple: true
            media_folder: "photos"
      - label: "Featured Event (shown in the navbar, footer, home page, attend page)"
        name: "featuredEvent"
        file: "src/pages/content/global/featuredEvent/featuredEvent.yaml"
        fields:
          - name: collectionId
            widget: hidden
            default: featuredEvent
          - name: slug
            label: Event
            widget: relation
            collection: events
            value_field: slug
            display_fields: ["displayName"]
            search_fields: ["displayName", "slug"]
          - name: displayName
            label: Display Name (navbar and footer)
            widget: string
          - name: show
            label: Show
            widget: boolean
            hint:
              Whether to show the featured event or not. If set to false, featured event sections
              will disappear from all the places where they would usually be.
  - label: "Events"
    name: events
    folder: "src/pages/content/events"
    create: true
    identifier_field: slug
    extension: yml
    fields:
      - name: collectionId
        widget: hidden
        default: event
      - name: slug
        label: Slug
        widget: string
        pattern:
          [
            "^[a-zA-Z0-9_-]+$",
            "it can be composed only of the letters of the English alphabet, digits, dashes, and underscores",
          ]
        hint: "The part of the URL which identifies an event."
      - name: displayName
        label: "Display name"
        widget: string
        hint: "The name of the event. For example, TEDxWarsaw 2020."
      - name: city
        label: City
        widget: string
        hint: "The city where the event takes place. Probably Warsaw."
      - name: date
        label: Date
        widget: datetime
        format: "DD/MM/YYYY"
        date_format: "DD/MM/YYYY"
        time_format: false
        picker_utc: true
      - name: hook
        label: Hook
        widget: text
        hint: A very short, attention grabbing piece of text. It's usually displayed next to the title of the event.
      - name: description
        label: Description
        widget: text
        hint: A couple of sentences that explain what the event is about, its theme, etc.
      - name: cover
        label: Cover
        widget: object
        hint: The topmost section on an event page.
        fields:
          - name: "variant"
            label: "Photo variant"
            widget: "select"
            hint: Use 'light' when the cover image is light, 'dark' when its dark. This will adjust the text's color appropriately.
            options: ["dark", "light"]
          - name: button
            label: Button
            widget: object
            fields:
              - name: text
                label: Text
                widget: string
              - name: link
                label: URL
                widget: string
                hint: The URL the button should point to.
              - name: show
                label: Show
                widget: boolean
                hint: Whether to show the button or not.
          - name: image
            label: Cover image
            widget: object
            fields:
              - name: mobile
                label: Mobile variant
                widget: image
                allow_multiple: false
                media_folder: "{{slug}}/coverPhotos"
              - name: desktop
                label: Desktop variant
                widget: image
                allow_multiple: false
                media_folder: "{{slug}}/coverPhotos"
      - name: location
        label: Location
        widget: object
        fields:
          - name: displayName
            label: Name
            hint: The name of the place where the event takes place.
            widget: string
          - name: city
            label: City
            hint: The city where the location is.
            widget: string
          - name: mapIframe
            label: Map HTML
            hint:
              A Google Maps embeddable map. To fill this field out, go on Google
              Maps, find a location, click "Share", then open the "Embed a map"
              tab, click "COPY HTML", and paste it here.
            widget: text
          - name: image
            label: Image
            hint: A background image.
            widget: image
            allow_multiple: false
            media_folder: "{{slug}}/locationPhoto"
      - name: callToAction
        label: The Red Section
        widget: object
        fields:
          - name: title
            widget: string
            label: Title
          - name: subtitle
            widget: string
            label: Subtitle
          - name: buttonText
            widget: string
            label: Button Text
          - name: buttonUrl
            widget: string
            label: Button URL
      - name: partnerLogoPaths
        label: Partner Logos
        widget: image
        allow_multiple: true
        media_folder: "{{slug}}/partnerLogos"
        media_library:
          config:
            multiple: true
      - name: speakerPhotoPaths
        label: Speaker photos
        widget: image
        allow_multiple: true
        media_folder: "{{slug}}/speakerPhotos"
        media_library:
          config:
            multiple: true
  - label: "Talks"
    name: talks
    folder: "src/pages/content/talks"
    create: true
    identifier_field: slug
    extension: yml
    fields:
      - name: collectionId
        widget: hidden
        default: talk
      - name: slug
        label: Slug
        widget: string
        pattern:
          [
            "^[a-zA-Z0-9_-]+$",
            "it can be composed only of the letters of the English alphabet, digits, dashes, and underscores",
          ]
        hint: "The part of the URL which identifies an event."
      - name: displayName
        label: "Display name"
        widget: string
        hint: "The name of the event. For example, TEDxWarsaw 2020."
      - name: speaker
        label: "Speaker"
        widget: string
        hint: "The speaker this talk"
      - name: eventSlug
        label: "Event"
        widget: relation
        collection: events
        value_field: slug
        display_fields: ["displayName"]
        search_fields: ["displayName", "slug"]
        hint: "Event hosting this talk"
      - name: cover
        label: Cover
        widget: object
        hint: The topmost section on an event page.
        fields:
          - name: image
            label: Cover image
            widget: object
            fields:
              - name: mobile
                label: Mobile variant
                widget: image
                allow_multiple: false
                media_folder: "{{slug}}/coverPhotos"
              - name: desktop
                label: Desktop variant
                widget: image
                allow_multiple: false
                media_folder: "{{slug}}/coverPhotos"
      - name: duration
        label: Duration
        widget: string
        hint: "Duration of this talk"
